#pragma once

#undef RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 96

#define TAPPING_FORCE_HOLD_PER_KEY
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_TERM 200

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE

